org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Work around Kotlin daemon incremental cache issues on Windows by compiling in-process.
# (Slower, but much more stable for development on some machines.)
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
